# Generated by Django 4.1.3 on 2022-12-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Telefon')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ulica zamieszkania')),
                ('building_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Numer domu/lokalu')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Kod pocztowy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
