# Generated by Django 4.1.3 on 2022-12-07 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ulica zamieszkania')),
                ('street_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Numer domu/lokalu')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Kod pocztowy')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Telefon')),
                ('created', models.DateField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
