# Generated by Django 4.1.3 on 2022-12-28 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_myuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ulica zamieszkania')),
                ('building_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Numer domu/lokalu')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Kod pocztowy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
