# Generated by Django 4.1.3 on 2022-12-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
