# Generated by Django 4.1.3 on 2022-12-28 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('pending_payment', 'Pending payment'), ('sent', 'Order sent'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='', max_length=100, verbose_name='Status zamówienia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ulica zamieszkania')),
                ('building_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Numer domu/lokalu')),
                ('city', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Kod pocztowy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Zamówiona ilość')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
