# Generated by Django 4.1.3 on 2022-12-28 20:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa kategorii')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna?')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa firmy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa produktu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Ilość w magazynie')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Cena')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Zdjęcie główne')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Opis produktu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
        ),
    ]
