# Generated by Django 4.1.3 on 2023-11-30 14:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa kategorii')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa firmy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa produktu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Ilość w magazynie')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Cena')),
                ('main_image', models.ImageField(default='', upload_to='', verbose_name='Zdjęcie główne')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Opis produktu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Tekst alternatywny (nazwa zdjęcia)')),
                ('image_number', models.IntegerField(null=True, verbose_name='Numer zdjęcia')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['image_number'],
            },
        ),
    ]
