# Generated by Django 4.1.3 on 2024-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productparameter_value_boolean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(default='', max_length=200, verbose_name='Opis parametru'),
        ),
    ]
