# Generated by Django 4.1.3 on 2024-02-28 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productparametervalue_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nazwa parametru produktu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=200, verbose_name='Opis parametru')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='productparametervalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productparametervalue',
            name='product_parameter',
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
        migrations.DeleteModel(
            name='ProductParameterValue',
        ),
    ]
