# Generated by Django 4.1.3 on 2024-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ManyToManyField(default='', to='products.category'),
        ),
    ]
