# Generated by Django 4.1.3 on 2024-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productattribute_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='display_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nazwa atrybutu do wyświetlenia'),
        ),
    ]
