# Generated by Django 4.1.3 on 2024-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productattribute_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='display_name',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='display_name_en',
            field=models.CharField(default='', max_length=200, verbose_name='Nazwa atrybutu do wyświetlenia (EN)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='display_name_pl',
            field=models.CharField(default='', max_length=200, verbose_name='Nazwa atrybutu do wyświetlenia (PL)'),
        ),
    ]
