# Generated by Django 4.1.3 on 2024-04-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_productattribute_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='display_name_en',
        ),
    ]
