# Generated by Django 4.1.3 on 2024-04-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_productattribute_display_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='display_name_pl',
            new_name='display_name',
        ),
    ]
